[package]
name = "nstc"
version = "0.1.0"
authors = ["Alex Konradi <alexkonradi@gmail.com>"]

[dependencies]
nalgebra = "0.16"
ncollide3d = "0.17"
nphysics3d = "0.9"
nphysics_testbed3d = "0.2"


[[bin]]
name = "nstc-view"
path = "src/view/view.rs"

[lib]
name = "nstc"
path = "src/lib.rs"
